### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by AckerApple** [AngularClass/angular-fx#3]
We've been using ngfx for angular1 for a long time. This project appears empty and not in development. Can you point us in the direction of ngfx for angular2 or any recommended solution for animations that worked so great like ngfx for angular1.

**Comment by traversng** [comment]
@AckerApple We are currently frozen until @angular/animations stabilizes. When it does, we will pick this up again.

**Comment by AckerApple** [comment]
I have already created a robust project to handle Angular2 animations. 

Would appreciate you and fellow peers review:

NPM - https://www.npmjs.com/package/ack-angular-fx
DEMO - https://ackerapple.github.io/ack-angular-fx/
